name: train
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow~=2.9.2
    - mltable~=1.4.1
    - azureml-mlflow~=1.54.0
    - azureml-dataprep[pandas]~=4.11.7
    - numpy~=1.24.1
    - scikit-learn~=1.3.2
    - fastparquet~=2023.10.1
