$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: training_pipeline
display_name: Training Pipeline
description: Training pipeline job with components using environment defined by a conda file.

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpucluster001
  continue_on_step_failure: false
  force_rerun: false

experiment_name: training

inputs:
  tracking_uri: azureml://northeurope.api.azureml.ms/mlflow/v1.0/subscriptions/dfbd9ec6-9c65-43d6-bb61-bf7c4e221d9d/resourceGroups/ent-ml-dev-app001/providers/Microsoft.MachineLearningServices/workspaces/ent-ml-dev-machinelearning001
  experiment_name: training
  model_name: supportvectorclassifier
  raw_data:
    type: mltable
    path: azureml:diabetes_mltable:1
  target_column_name: "Y"
  test_size: 0.2

outputs:
  train_data:
    type: mltable
    mode: rw_mount
  test_data:
    type: mltable
    mode: rw_mount
  best_model:
    type: mlflow_model
  validation_report:
    type: uri_folder
    mode: rw_mount

jobs:
  preprocess:
    type: command
    component: ./preprocess/component.yml
    compute: azureml:cpucluster001
    inputs:
      tracking_uri: ${{parent.inputs.tracking_uri}}
      experiment_name: ${{parent.inputs.experiment_name}}
      test_size: ${{parent.inputs.test_size}}
      input_data: ${{parent.inputs.raw_data}}
    outputs:
      output_data_train: ${{parent.outputs.train_data}}
      output_data_test: ${{parent.outputs.test_data}}

  train:
    type: command
    component: ./train/component.yml
    compute: azureml:cpucluster001
    inputs:
      tracking_uri: ${{parent.inputs.tracking_uri}}
      experiment_name: ${{parent.inputs.experiment_name}}
      svr_kernel: 'rbf'
      svr_degree: 3
      target_column_name: ${{parent.inputs.target_column_name}}
      input_data: ${{parent.jobs.preprocess.outputs.output_data_train}}
    outputs:
      output_data: ${{parent.outputs.best_model}}

  validate:
    type: command
    component: ./validate/component.yml
    compute: azureml:cpucluster001
    inputs:
      tracking_uri: ${{parent.inputs.tracking_uri}}
      experiment_name: ${{parent.inputs.experiment_name}}
      target_column_name: ${{parent.inputs.target_column_name}}
      model_name: ${{parent.inputs.model_name}}
      input_data: ${{parent.jobs.preprocess.outputs.output_data_test}}
      input_model: ${{parent.jobs.train.outputs.output_data}}
    outputs:
      output_data: ${{parent.outputs.validation_report}}
