$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: training_pipeline
display_name: Training Pipeline
description: Training pipeline job with components using environment defined by a conda file.

settings:
  default_datastore: azureml:entmldevlake001data
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false
  force_rerun: false

experiment_name: training
jobs:
  preprocess:
    type: command
    component: ./preprocess/component.yml
    compute: azureml:cpu-cluster

  train:
    type: command
    component: ./train/component.yml
    compute: azureml:cpu-cluster

  validate:
    type: command
    component: ./validate/component.yml
    compute: azureml:cpu-cluster
