name: preprocess
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow~=2.0.1
    - mltable~=1.0.0
    - azureml-mlflow~=1.48.0
    - azureml-dataprep[pandas]~=4.8.3
    - pandas~=1.5.2
    - scikit-learn~=1.2.0
