name: score
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow~=2.1.1
    - azureml-mlflow~=1.48.0
    - azureml-dataprep[pandas]~=4.8.3
    - numpy~=1.24.1
    - azureml-core~=1.48.0
    - azureml-dataset-runtime[fuse]~=1.48.0
    - opencensus~=0.11.0
    - opencensus-ext-logging~=0.1.1
    - opencensus-ext-azure~=1.1.7
    - inference-schema~=1.4
