name: Infra Validation Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
    secrets:
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      TEAMS_WEBHOOK_URI:
        required: true
        description: "Teams webhook URL for notification."

permissions:
  id-token: write
  contents: read

jobs:
  train:
    name: Validation of ${{ inputs.environment }}
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: ${{ inputs.environment }}
    outputs:
      job_name: ${{ steps.aml_job.outputs.job_name }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Create Dataset
      - name: Create Dataset
        id: aml_dataset
        run: |
          az ml data update \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ vars.AZURE_ML_WORKSPACE_NAME }} \
            --file ${{ github.workspace }}/code/ml/data/diabetes_mltable.yml

      # Create Job
      - name: Create Job
        id: aml_job
        run: |
          JOB_NAME
          az ml job create \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ vars.AZURE_ML_WORKSPACE_NAME }} \
            --name $JOB_NAME \
            --file ${{ github.workspace }}/code/ml/data/diabetes_mltable.yml \
            --stream

          echo "job_name=$JOB_NAME" >> $GITHUB_OUTPUT
        env:
          JOB_NAME: "Job-${{ github.sha }}"

      # Teams notification
      - name: Teams notification
        uses: jdcargile/ms-teams-notification@v1.3
        id: teams_notification
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          notification-summary: New model has been trained. Please review and approve promotion to production
          notification-color: 17a2b8
          timezone: UTC

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: "agentazcliversion"
          inlineScript: |
            az logout
