name: Infra Deployment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
    secrets:
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_ID:
        required: true
        description: "Specifies the client id."

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Deployment to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    continue-on-error: false
    if: github.event_name == 'push' || github.event_name == 'release'
    environment: ${{ inputs.environment }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ inputs.azure_subscription_id }}

      # Deploy Template
      - name: Deploy Template
        id: deployment_run
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ inputs.azure_subscription_id }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ vars.AZURE_LOCATION }}
          template: ${{ github.workspace }}/infra/main.bicep
          parameters: ${{ github.workspace }}/infra/params.${{ inputs.environment }}.json
          deploymentMode: Incremental
          deploymentName: "${{ inputs.environment }}-${{ github.sha }}"
          failOnStdErr: false

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: "agentazcliversion"
          inlineScript: |
            az logout
