name: Infra Validation Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
    secrets:
      tenant_id:
        required: true
        description: "Specifies the tenant id of the deployment."
      client_id:
        required: true
        description: "Specifies the client id."

permissions:
  id-token: write
  contents: read

jobs:
  validation:
    name: Validation of ${{ inputs.environment }}
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: ${{ inputs.environment }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.client_id }}
          tenant-id: ${{ secrets.tenant_id }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Deploy Template - validation
      - name: Deploy Template - validation
        id: deployment_validation
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ vars.AZURE_LOCATION }}
          template: ${{ github.workspace }}/infra/main.bicep
          parameters: ${{ github.workspace }}/infra/params.${{ inputs.environment }}.json
          deploymentMode: Validate
          deploymentName: "App-${{ github.sha }}"
          failOnStdErr: false

      # Deploy Template - what-if
      - name: Deploy Template - what-if
        id: deployment_whatif
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ vars.AZURE_LOCATION }}
          template: ${{ github.workspace }}/infra/main.bicep
          parameters: ${{ github.workspace }}/infra/params.${{ inputs.environment }}.json
          deploymentMode: Incremental
          deploymentName: "App-${{ github.sha }}"
          failOnStdErr: false
          additionalArguments: "--what-if --what-if-exclude-change-types Ignore NoChange Unsupported --what-if-result-format FullResourcePayloads"

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: "agentazcliversion"
          inlineScript: |
            az logout
