name: Infra Deployment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
    secrets:
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
    outputs:
      machine_learning_name:
        description: "The name of the machine learning workspace."
        value: ${{ jobs.deployment.outputs.machine_learning_name }}
      machine_learning_online_endpoint_name:
        description: "The name of the machine learning workspace online endpoints."
        value: ${{ jobs.deployment.outputs.machine_learning_online_endpoint_name }}

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Deployment to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    continue-on-error: false
    if: github.event_name == 'push' || github.event_name == 'release'
    environment: ${{ inputs.environment }}
    outputs:
      machine_learning_name: ${{ steps.create_outputs.outputs.machine_learning_name }}
      machine_learning_online_endpoint_name: ${{ steps.create_outputs.outputs.machine_learning_online_endpoint_name }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Deploy Template
      - name: Deploy Template
        id: deployment_run
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          region: ${{ vars.AZURE_LOCATION }}
          template: ${{ github.workspace }}/infra/main.bicep
          parameters: ${{ github.workspace }}/infra/params.${{ inputs.environment }}.json
          deploymentMode: Incremental
          deploymentName: "${{ inputs.environment }}-${{ github.sha }}"
          failOnStdErr: false

      # Create Outputs
      - name: Create Outputs
        id: create_outputs
        run: |
          echo "machine_learning_name=${{ steps.deployment_run.outputs.machineLearningName }}" >> $GITHUB_OUTPUT
          echo "machine_learning_online_endpoint_name=${{ steps.deployment_run.outputs.machineLearningOnlineEndpointName }}" >> $GITHUB_OUTPUT

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: "agentazcliversion"
          inlineScript: |
            az logout
