name: Dev Deployment
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"
      - "code/synapseParameters/**"
      - "infra/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"
      - "code/synapseParameters/**"
      - "infra/**"

jobs:
  infra_validation_dev:
    uses: ./.github/workflows/_infraValidationTemplate.yml
    name: "Validation of IaC templates - Dev"
    with:
      environment: "dev"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

  infra_deployment_dev:
    uses: ./.github/workflows/_infraDeploymentTemplate.yml
    name: "Deployment of IaC templates - Dev"
    needs: [infra_validation_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
