name: Dev Deployment
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"
      - "code/synapseParameters/**"
      - "infra/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"
      - "code/synapseParameters/**"
      - "infra/**"

jobs:
  infra_validation_dev:
    uses: ./.github/workflows/_infraValidationTemplate.yml
    name: "Validation of IaC templates - Dev"
    with:
      environment: "dev"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

  infra_deployment_dev:
    uses: ./.github/workflows/_infraDeploymentTemplate.yml
    name: "Deployment of IaC templates - Dev"
    needs: [infra_validation_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

  aml_training_dev:
    uses: ./.github/workflows/_amlTrainTemplate.yml
    name: "Azure ML Training - Dev"
    needs: [infra_deployment_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      TEAMS_WEBHOOK_URI: ${{ secrets.TEAMS_WEBHOOK_URI }}

  aml_model_promotion_dev_to_prd:
    uses: ./.github/workflows/_amlModelPromotionTemplate.yml
    name: "Azure ML Model Promotion - Dev to Prod"
    needs: [aml_training_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment_source: "dev"
      environment_destination: "prd"
      job_name: ${{ needs.train.outputs.job_name }}
      output_name: best_model
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
