name: Prod Deployment
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"
      - "code/synapseParameters/**"
      - "infra/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"
      - "code/synapseParameters/**"
      - "infra/**"

jobs:
  infra_validation_prd:
    uses: ./.github/workflows/_infraValidationTemplate.yml
    name: "Validation of IaC templates - Prd"
    with:
      environment: "prd"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

  infra_deployment_prd:
    uses: ./.github/workflows/_infraDeploymentTemplate.yml
    name: "Deployment of IaC templates - Prd"
    needs: [infra_validation_prd]
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    with:
      environment: "prd"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

  aml_deploy_prd:
    uses: ./.github/workflows/_amlDeployTemplate.yml
    name: "Azure ML Deploy - Prd"
    needs: [infra_deployment_prd]
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    with:
      environment: "prd"
      machine_learning_online_endpoint_name: ${{ needs.infra_deployment_prd.outputs.machine_learning_online_endpoint_name }}
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
