name: Python - Lint and Test
on:
  push:
    branches:
      - main
    paths:
      - "code/**"
      - "tests/**"
      - "requirements.txt"
      - "requirements-dev.txt"
      - ".github/workflows/python.yml"
  pull_request:
    branches:
      - main
    paths:
      - "code/**"
      - "tests/**"
      - "requirements.txt"
      - "requirements-dev.txt"
      - ".github/workflows/python.yml"

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      # Setup Python 3.10
      - name: Setup Python 3.10
        id: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Run Python Linting
      - name: Run Python Linting
        id: python_linti
        run: |
          pip install -r requirements-dev.txt -q
          git init
          git add *
          pre-commit install --install-hooks
          pre-commit run --all-files --verbose

      # Run Python Tests
      - name: Run Python Tests
        id: python_test
        run: |
          pip install -r requirements.txt -q
          # python -m pytest
